### ISSUE TITLE
ssh一直没成功

### ISSUE THREAD

**Issue by manipulative** [openp2p-cn/openp2p#14]
是否是我输入的命令不对呢？
我的配置如下
![image](https://user-images.githubusercontent.com/26652791/196949449-5a8c03d8-1145-4fb0-b9f7-60a3bcf4ef92.png)

ssh时输入的命令如下：
`ssh username@127.0.0.1:23390`
望解惑！谢谢

**Comment by TenderIronh** [comment]
截图上显示connecting呢，等连上就可以了。

**Comment by manipulative** [comment]
谢谢 已解决
