### ISSUE TITLE
Win10-win10 ftp链接问题

### ISSUE THREAD

**Issue by SoulLinkIly** [openp2p-cn/openp2p#19]
使用https://www.20cn.net/ mini ftp 在A建立21端口匿名用户
B使用127.0.0.1:211 访问，始终访问不了，搞不明白卡在哪里了

**Comment by vip123456789** [comment]
你不能使用ftp工具。因为ftp在使用的时候实际上是启用了2个端口，21端口只是负责通讯，还会随机启用一个端口用来传输数据。你用openp2p只是打通了一个端口，另一个随机端口没有打通。推荐使用别的http文件服务器，只使用一个端口。比如https://github.com/sigoden/dufs

**Comment by SoulLinkIly** [comment]
感谢解惑！
