### ISSUE TITLE
Windows Defender 报毒

### ISSUE THREAD

**Issue by Guanran928** [openp2p-cn/openp2p#22]
测试环境： Windows 8.1 Build 9600
显示为 Trojan:Script/Wacatac.B!ml
![Capture](https://user-images.githubusercontent.com/68757440/207225672-81111157-66bd-410c-b0d7-9370d9629ad0.PNG)

**Comment by TenderIronh** [comment]
源码都公开的，放心没毒。windows要购买他家的证书签名才不报毒
