### ISSUE TITLE
P2PNetwork init error

### ISSUE THREAD

**Issue by Beckeet** [openp2p-cn/openp2p#23]
2022/12/19 18:02:50 11224 INFO init start
2022/12/19 18:02:55 11224 ERROR NAT detect error:read udp [::]:57994: i/o timeout
2022/12/19 18:03:02 11224 ERROR P2PNetwork init error:read udp [::]:57994: i/o timeout
2022/12/19 18:03:02 11224 INFO init start
2022/12/19 18:03:02 11224 INFO autorunApp start

无法连上网络，求大佬解决

**Comment by TenderIronh** [comment]
服务器问题，fixed
