### ISSUE TITLE
to many open files 问题

### ISSUE THREAD

**Issue by manipulative** [openp2p-cn/openp2p#24]
macOS在想尝试update时发生如下报错：
···
ERROR update:query update list failed:Get "https://api.openp2p.cn:xxxx/api/v1/update?fromver=3.5.5&os=darwin&arch=arm64": dial tcp: lookup api.openp2p.cn on xxx.xxx.xxx.xxx:xxx: dial udp xxx.xxx.xxx.xxx:xx: socket: too many open files
···
请问该如何解决呢

**Comment by TenderIronh** [comment]
某些情况会导致新建socket数量比较大导致。程序启动时缺了调用Setrlimit，后面补上

**Comment by TenderIronh** [comment]
v3.6.5 fixed. setRlimit 65536
