### ISSUE TITLE
The process cannot access the file because it is being used by another process.

### ISSUE THREAD

**Issue by ttnspike** [openp2p-cn/openp2p#25]
ERROR os.OpenFile C:\Program Files\OpenP2P\openp2p.exe error:open C:\Program Files\OpenP2P\openp2p.exe: The process cannot access the file because it is being used by another process.
卸载后，重新安装还是报错。。。求解

**Comment by TenderIronh** [comment]
可以试试手动把openp2p.exe进程结束掉。也可能是安全软件限制了
