### ISSUE TITLE
关于协议支持的问题

### ISSUE THREAD

**Issue by RidePig** [openp2p-cn/openp2p#26]
在创建P2P应用时，只能选择TCP或者UDP协议。请问可以支持同时使用两种协议吗？

**Comment by RidePig** [comment]
请问是会在下一个版本更新修复吗？当前版本仍然无法做到一个端口同时使用两种协议。

**Comment by TenderIronh** [comment]
已经修复了的，可能是浏览器缓存导致。ctrl+f5强制刷新试试
