### ISSUE TITLE
移动家庭宽带无法访问openp2p.cn？

### ISSUE THREAD

**Issue by wmdny** [openp2p-cn/openp2p#28]
尝试在家中电脑上使用openp2p，但是浏览器始终无法访问openp2p.cn。
更换为手机热点后能正常使用。
家中的网络是移动宽带。
想问是运营商或是openp2p做了限制？

**Comment by wmdny** [comment]
家中的电脑安装了客户端，但在console控制台中显示橙色离线。

**Comment by TenderIronh** [comment]
openp2p本身不会限制运营商。移动宽带ping api.openp2p.cn和openp2p.cn是什么ip？

**Comment by wmdny** [comment]
分别是124.221.80.223和101.32.30.151。另外补充现象，之前显示离线是家中电脑待机休眠了。移动宽带下我的电脑能正常显示在线。也可以远程办公室的电脑，但办公室中电脑无法远程家中电脑。我使用手机4G访问控制台成功后连接Wi-Fi无法刷新界面。

**Comment by wmdny** [comment]
@TenderIronh 客户端连接家中Wi-Fi即使显示在线。办公室另一台电脑也无法3389远程家中电脑。即使应用中显示直连成功。

**Comment by wmdny** [comment]
@TenderIronh 还有一个现象。在我手机连接家中Wi-Fi时，多次尝试后偶然能打开openP2p.cn，但无法登录。而且部分静态资源好像没加载成功。切换到4g或5g后，秒加载成功。手机运营商电信

**Comment by wmdny** [comment]
当然，也可能我的宽带运营商做了限制。平常访问一些“奇怪的网站”时也会被限制。访问github都得看它心情。我现在就是手机流量才能访问GitHub

**Comment by TenderIronh** [comment]
运营商问题无法解决
