### ISSUE TITLE
Win10家庭版就算是用这个也没法远程连接吗？

### ISSUE THREAD

**Issue by xiaoBingge114514** [openp2p-cn/openp2p#51]
T.T

**Comment by Guailoudou** [comment]
这个只能提供网络上的连接，系统不支持是没办法的，你可以使用市面上常见的远程控制软件如todesk来满足你的需求

**Comment by pjy612** [comment]
用这个 估计能从 家庭版 远程别的。。。但是 从别的远程 家庭版 应该不行。。。
不过可以试试 家庭版装个VNC啥的。。。

**Comment by MC-XiaoHei** [comment]
请检查是否开启远程控制功能
家庭默认似乎并不开启此功能

**Comment by CtrlAltDelet** [comment]
家庭版没这功能，有个软件可以开启rdp我记得，或者激活个专业版呗

**Comment by lentikr** [comment]
填个激活码的事，很简单的
