### ISSUE TITLE
建议公布个防火墙端口放行规则

### ISSUE THREAD

**Issue by ayakaqingyue** [openp2p-cn/openp2p#70]
如题，在部分FTTR和大部分专业防火墙进行NAT的环境中，需要对打洞的通讯端口进行映射来获取Cone NAT，不然默认是Symmetric NAT

比如zerotier的9993，以及tailscale的udp41641。

目前这个软件的通讯发起端口不明确，就导致了只能通过设置DMZ来获取Cone NAT，但是这样意味着只有一台设备能Cone NAT，别的设备都只能Symmetric NAT

**Comment by Shaw-Yee** [comment]
2024.6.14 服务器默认UDP    27183
客户端默认UDP 27182  27183

可以通过 配置文件修改客户端 UDP TCP端口
C:\Program Files\OpenP2P\config.json 
 /usr/local/openp2p/config.json

**Comment by TenderIronh** [comment]
![图片](https://github.com/openp2p-cn/openp2p/assets/89245779/ff1a36ca-2669-4cb7-b51e-893f9b4b24d3)
