### ISSUE TITLE
服务端不开源个吗

### ISSUE THREAD

**Issue by 6triker** [openp2p-cn/openp2p#74]

**Comment by dissipator** [comment]
编译失败，
openp2p-gateway imports
	github.com/gin-gonic/gin imports
	github.com/gin-gonic/gin/binding imports
	gopkg.in/yaml.v2 tested by
	gopkg.in/yaml.v2.test imports
	gopkg.in/check.v1 imports
	github.com/kr/pretty imports
	github.com/kr/text: github.com/openp2p-cn/totp@v0.0.0-20230102121327-8e02f6b392ed: invalid version: unknown revision 8e02f6b392ed
[opc@instance--1250 gateway-lite]$ go build
web.go:10:2: missing go.sum entry for module providing package github.com/gin-gonic/gin (imported by openp2p-gateway); to add:
	go get openp2p-gateway
web.go:11:2: missing go.sum entry for module providing package github.com/golang-jwt/jwt (imported by openp2p-gateway); to add:
	go get openp2p-gateway
wssession.go:12:2: missing go.sum entry for module providing package github.com/gorilla/websocket (imported by openp2p-gateway); to add:
	go get openp2p-gateway
pushhandler.go:11:2: missing go.sum entry for module providing package github.com/openp2p-cn/totp (imported by openp2p-gateway); to add:
	go get openp2p-gateway
[opc@instance--1250 gateway-lite]$ go version
go version go1.18.1 linux/amd64



docker 运行报错。
/openp2p-gateway: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /openp2p-gateway)
/openp2p-gateway: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /openp2p-gateway)
