### ISSUE TITLE
日志打印出重未用过的设备登录和授权

### ISSUE THREAD

**Issue by flysa** [openp2p-cn/openp2p#76]
![image](https://github.com/openp2p-cn/openp2p/assets/12538204/a4cd2b71-c6da-4086-af09-8a7ede46ab25)

**Comment by Guailoudou** [comment]
这是openp2p的共享机制，属正常现象，可自行设置共享带宽

**Comment by TenderIronh** [comment]
对的

> 这是openp2p的共享机制，属正常现象，可自行设置共享带宽
