### ISSUE TITLE
所有连接都是直连或者通过其它节点(非服务器)转发的?完全不需要不经过服务器转发吗

### ISSUE THREAD

**Issue by LysLee111** [openp2p-cn/openp2p#78]
目前的直连成功率是多少？
这和目前主流的远程软件TeamViewer, ToDesk, 向日葵技术上有啥区别？(当然这个不收费)

有没有微信群？现在谁还用QQ啊

**Comment by TenderIronh** [comment]
不走服务器。只有自己的设备，或者别人共享的
