### ISSUE TITLE
是否能实现不同局域网间相互访问

### ISSUE THREAD

**Issue by chn-maich** [openp2p-cn/openp2p#86]
比如A电脑网络192.168.20.x
B电脑网络192.168.100.x
C电脑网络192.168.200.x

在A电脑直接请求C电脑局域网或者B电脑局域网下的服务

**Comment by TenderIronh** [comment]
可以的。前提C或B是Llinux系统，依赖iptables snat
在C节点点击“编辑”，“网络资源”里输入“192.168.200.0/24"
