### ISSUE TITLE
Server status?

### ISSUE THREAD

**Issue by penglb3** [openp2p-cn/openp2p#9]
Software Version: 3.1.0
OS: Windows 10 Pro / Home China

自从昨天上午开始我的所有p2p app都无法连接成功。所有机器都能检测到在线，但是所有app一直显示正在连接。
使用了不同网络下的几台设备测试，全都一样一直无法连接，因此暂时考虑服务器方面原因可能性更大。
想询问一下当前的服务器状态？
此外，如果可以的话，是否可以做一个简单的服务器状态/数量显示功能？这样用户可以知道是自己的网络问题还是服务器问题。

Since yesterday morning, all my p2p apps couldn't establish connection. Console shows that all machines are online but all apps are "connecting". 
I've tested on several devices under difference networks. The results are the same - unable to connect. So IMO it is more likely due to the server(s). 
Could you please tell me the current status of servers?
By the way, is it possible to implement a function that shows server numbers / status so that users could know if the problem is on their network or servers?

**Comment by TenderIronh** [comment]
是那天上午才出现不成功，还是一直不行？
你能在web console看到p2p app的状态，说明服务器是正常的。建议查看两端节点日志，看有什么错误。

**Comment by penglb3** [comment]
一直不行。我截取了在一台机子上显示的log，之前的log基本就是这一段的各种循环：

2022/06/08 18:03:30 6856 INFO addApp 远程PC to [NODE1]:localhost:3389 start
2022/06/08 18:03:30 6856 ERROR direct connect failed, try to relay
2022/06/08 18:03:30 6856 INFO addRelayTunnel to [NODE1] start
2022/06/08 18:03:30 6856 INFO got relay node:goodtoseeyou
2022/06/08 18:03:40 6856 ERROR wait msg7:1 timeout
2022/06/08 18:03:40 6856 ERROR init error:peer offline
2022/06/08 18:03:40 6856 ERROR direct connect error:peer offline
2022/06/08 18:03:40 6856 INFO addRelayTunnel to [NODE1] end
2022/06/08 18:03:40 6856 INFO addApp 远程PC to [NODE1]:localhost:3389 end
2022/06/08 18:03:45 6856 INFO MsgPushReportApps
2022/06/08 18:03:45 6856 INFO MsgPushReportApps
2022/06/08 18:03:51 6856 INFO detect app 远程PC(0) disconnect, reconnecting the 1 times...

**Comment by penglb3** [comment]
看这样子，是能和服务器通信，但是连不上任何中继节点？如果是这样的话那看来问题还是机子所在的网络？……那基本就寄了。

**Comment by TenderIronh** [comment]
2022/06/08 18:03:30 6856 INFO addRelayTunnel to [NODE1] start
远程节点叫[NODE1]，这里有问题啊，节点名字最少8个字符的。
另外日志显示peer offline，看看peer客户端是否在线  
看看两个节点的版本是否最新

**Comment by penglb3** [comment]
1. [NODE1]这个节点名字是我手动改的（出于隐私保护目的），原始log里面不叫这个名字。忘了说了。
2. Console显示两边客户端都在线，版本都是3.1.0。
![屏幕截图 2022-06-09 104108](https://user-images.githubusercontent.com/58880775/172752709-4ff26e31-5230-4063-aa8f-a8b866b4feef.png)

**Comment by TenderIronh** [comment]
手抖了，把3版本的认证流程token搞错了。导致没法使用共享中转节点。请升级至最新版本

**Comment by penglb3** [comment]
ok了，感谢！您辛苦了！

**Comment by TenderIronh** [comment]
version 3 has refactored the connection and auth process. But a little bug lead to unable to use public relay node.
I also add the "public relay node" to autotest case
